url: https://curenova.github.io
baseurl: 

# Site settings
title: Renova
email: your-email@domain.com
description: "CU-Boulder's New Music Choir"

# Team names, titles and social links
people:
- name: Jessie Flasschoen-Cambell
  pic: 1
  position: Conductor
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: stack-overflow
#       url: #

# - name: Corey Murphey
#   pic: 2
#   position: Webmaster
# #   social:
# #     - title: twitter
# #       url: #
# #     - title: facebook
# #       url: #
# #     - title: linkedin
# #       url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: instagram
    url: 
  - title: soundcloud
    url: 
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
  - title: github
    url: https://curenova.github.io

# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
